/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sandbox_IsATTY */

#ifndef _Included_sandbox_IsATTY
#define _Included_sandbox_IsATTY
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sandbox_IsATTY
 * Method:    isatty
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_sandbox_IsATTY_isatty
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
