[versions]
okhttp =  '4.9.3'
bytebuddy = '1.12.8'
junit-jupiter =  '5.8.2'


[libraries]
commons-math = { group = "org.apache.commons", name = "commons-math3", version = "3.6.1" }
guava = { module = "com.google.guava:guava", version = "31.0.1-jre" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-tls = { group = "com.squareup.okhttp3", name = "okhttp-tls", version.ref = "okhttp" }
okhttp-dnsoverhttps = { group = "com.squareup.okhttp3", name = "okhttp-dnsoverhttps", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
conscrypt = { module = "org.conscrypt:conscrypt-openjdk-uber", version = "2.5.2" }

bytebuddy = { group = "net.bytebuddy", name = "byte-buddy", version.ref = "bytebuddy" }
bytebuddy-agent = { group = "net.bytebuddy", name = "byte-buddy-agent", version.ref = "bytebuddy" }

junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }
assertj = { module = "org.assertj:assertj-core", version = "3.22.0" }
testcontainers = { module = "org.testcontainers:testcontainers", version = "1.16.3" }

jna = { module = "net.java.dev.jna:jna", version = "5.11.0" }
jnr-ffi = { module = "com.github.jnr:jnr-ffi", version = "2.2.11" }


[bundles]
okhttp = ['okhttp', 'okhttp-tls', 'okhttp-dnsoverhttps', 'okhttp-logging']
bytebuddy = ['bytebuddy', 'bytebuddy-agent']


[plugins]
