#
# sandbox
#
# Copyright (c) 2021,today - Brice Dutheil <brice.dutheil@gmail.com>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
[versions]
okhttp =  "4.9.3"
bytebuddy = "1.12.9"
junit-jupiter =  "5.8.2"
graalvm = "22.1.0"


[libraries]
commons-math = { group = "org.apache.commons", name = "commons-math3", version = "3.6.1" }
guava = { module = "com.google.guava:guava", version = "31.0.1-jre" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-tls = { group = "com.squareup.okhttp3", name = "okhttp-tls", version.ref = "okhttp" }
okhttp-dnsoverhttps = { group = "com.squareup.okhttp3", name = "okhttp-dnsoverhttps", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
conscrypt = { module = "org.conscrypt:conscrypt-openjdk-uber", version = "2.5.2" }

bytebuddy = { group = "net.bytebuddy", name = "byte-buddy", version.ref = "bytebuddy" }
bytebuddy-agent = { group = "net.bytebuddy", name = "byte-buddy-agent", version.ref = "bytebuddy" }

junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }
assertj = { module = "org.assertj:assertj-core", version = "3.22.0" }
testcontainers = { module = "org.testcontainers:testcontainers", version = "1.17.1" }

jna = { module = "net.java.dev.jna:jna", version = "5.11.0" }
jnr-ffi = { module = "com.github.jnr:jnr-ffi", version = "2.2.12" }

graal-sdk = { module = "org.graalvm.sdk:graal-sdk", version.ref = "graalvm" }
graal-js = { module = "org.graalvm.js:js", version.ref = "graalvm" }
graal-js-scriptengine = { module = "org.graalvm.js:js-scriptengine", version.ref = "graalvm" }


[bundles]
okhttp = ['okhttp', 'okhttp-tls', 'okhttp-dnsoverhttps', 'okhttp-logging']
bytebuddy = ['bytebuddy', 'bytebuddy-agent']
graal-js = ["graal-js", "graal-js-scriptengine"]

[plugins]
